if(true){
  console.log(
    " -yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-\n",
    "-yyyyyyyyyyyyyyyyyys    syyyyyyyyyyyyyyyyyy-\n",
    "-MMMMMMMMMMMMMMM           NMMMMMMMMMMMMMMM-\n",
    "-MMMMMMMMMMMN        _         MMMMMMMMMMMM-\n",
    "-MMMMMMMMmhs      shmMNmy       ydNMMMMMMMM-\n",
    "-MMMMNdy       ydNN      NNhs      shmMMMMM-\n",
    "-Mmhs      shmN             NNdy       ydNM-\n",
    "-       ydNNdy                ymNNds      s-\n",
    "-    hNMmhs                      shNMmy    -\n",
    "-   sMN      ssssss      ssssss     sMm    -\n",
    "-   sMm      MMMMMMm    mMMMMMM      Mm    -\n",
    "-   sMm      MMMMMMMMMMMMMMMMMM      Mm    -\n",
    "-   sMm      MMMMMMMMMMMMMMMMMM      Mm    -\n",
    "-   sMm      MMMN          NMMM      Mm    -\n",
    "-   sMm      MMMMMMM    MMMMMMM      Mm    -\n",
    "-   sMm      MMMMMMM    MMMMMMM      Mm    -\n",
    "-   sMm      MMMMMMM    MMMMMMM      Mm    -\n",
    "-   sMm      MMMMMMM    MMMMMMM      Mm    -\n",
    "-    dNNdy                        ymMNh    -\n",
    "-      shNMmh                 shNMdy       -\n",
    "-Ndy       hdNNds          ymNNds       ydN-\n",
    "-MMMMmh       shmMmys  shNMmy       shmMMMM-\n",
    "-MMMMMMMNds       ymMNMNhs       ymMMMMMMMM-\n",
    "-MMMMMMMMMMMmys      ^       shNMMMMMMMMMMM-\n",
    "-MMMMMMMMMMMMMMNdy        ydNMMMMMMMMMMMMMM-\n",
    "-ddddddddddddddddddy///shdddddddddddddddddd-\n",
    "-dddddddddddddddddddddddddddddddddddddddddd-\n",
  );
}
